import { useState, useRef } from 'react';
import { Link, useNavigate, Navigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { motion } from 'framer-motion';
import {
  Play, ArrowRight, ArrowLeft, Dumbbell, Flame,
  Apple, Brain, ChevronRight, Star, Users, Trophy, Zap
} from 'lucide-react';

const programs = [
  {
    icon: Flame,
    title: 'Cardio Strength',
    desc: 'High-intensity cardio workouts designed to build your cardiovascular endurance and burn maximum calories.',
    color: 'bg-primary text-background',
    accent: 'border-primary',
  },
  {
    icon: Dumbbell,
    title: 'Fat Loss',
    desc: 'Targeted protocols combining resistance training and strategic cardio to accelerate fat burning.',
    color: 'bg-surface text-white',
    accent: 'border-white/10',
  },
  {
    icon: Trophy,
    title: 'Muscle Gain',
    desc: 'Progressive overload programs engineered to maximize hypertrophy and build raw strength.',
    color: 'bg-surface text-white',
    accent: 'border-white/10',
  },
  {
    icon: Apple,
    title: 'Nutrition',
    desc: 'Science-backed meal planning and macro tracking for optimal body composition and performance.',
    color: 'bg-surface text-white',
    accent: 'border-white/10',
  },
  {
    icon: Brain,
    title: 'AI Blueprint',
    desc: 'Personalized plans generated by our ML model based on your biological metrics and goals.',
    color: 'bg-surface text-white',
    accent: 'border-white/10',
  },
];

const stats = [
  { value: '10K+', label: 'Satisfied Members', icon: Users },
  { value: '50+', label: 'Expert Coaches', icon: Trophy },
  { value: '200+', label: 'Workout Programs', icon: Dumbbell },
  { value: '98%', label: 'Success Rate', icon: Star },
];

const avatars = [
  'https://randomuser.me/api/portraits/men/32.jpg',
  'https://randomuser.me/api/portraits/women/44.jpg',
  'https://randomuser.me/api/portraits/men/56.jpg',
];

const HomePage = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [activeCard, setActiveCard] = useState(0);
  const [scrollIdx, setScrollIdx] = useState(0);
  const cardRef = useRef(null);

  // Determine dashboard route for logged-in users
  const dashboardPath = user ? (user.role === 'Admin' ? '/admin' : user.role === 'Coach' ? '/coach' : '/customer') : '';

  const scrollCards = (dir) => {
    const next = scrollIdx + dir;
    if (next >= 0 && next <= programs.length - 3) {
      setScrollIdx(next);
      setActiveCard(next);
    }
  };

  return (
    <div className="overflow-x-hidden">

      {/* ─── Premium Hero Section ─────────────────────────────────────────── */}
      <section className="relative min-h-[95vh] flex items-center pt-24 pb-12 overflow-hidden">
        {/* Elite Background Effects */}
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-[-10%] left-[-10%] w-[50vw] h-[50vw] bg-primary/20 rounded-full blur-[120px] mix-blend-screen opacity-50 animate-pulse" />
          <div className="absolute bottom-[-10%] right-[-10%] w-[40vw] h-[40vw] bg-secondary/20 rounded-full blur-[100px] mix-blend-screen opacity-50" />
          <div className="absolute top-[30%] left-[40%] w-[20vw] h-[20vw] bg-white/5 rounded-full blur-[80px]" />
          {/* Subtle Grid Pattern Overlay */}
          <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0MCIgaGVpZ2h0PSI0MCI+CjxwYXRoIGQ9Ik0wIDBoNDB2NDBIMHoiIGZpbGw9Im5vbmUiLz4KPHBhdGggZD0iTTAgMGg0MHYxSDB6bTAgMzl2MWg0MHYtMXonIGZpbGw9InJnYmEoMjU1LDI1NSwyNTUsMC4wNSkiLz4KPHBhdGggZD0iTTAgMHY0MGgxVjB6bTM5IDB2NDBoMVYweiIgZmlsbD0icmdiYSgyNTUsMjU1LDI1NSwwLjA1KSIvPgo8L3N2Zz4=')] opacity-20" />
          <div className="absolute inset-0 bg-gradient-to-b from-transparent via-background/80 to-background" />
        </div>

        <div className="container mx-auto px-4 grid grid-cols-1 lg:grid-cols-12 gap-8 items-center relative z-10">
          {/* Left Content (Spans 7 columns on LG) */}
          <motion.div 
            initial={{ opacity: 0, y: 30 }} 
            animate={{ opacity: 1, y: 0 }} 
            transition={{ duration: 0.8, ease: "easeOut" }}
            className="lg:col-span-7 space-y-10"
          >
            {/* Elegant Badge */}
            <motion.div 
              initial={{ opacity: 0, x: -20 }} 
              animate={{ opacity: 1, x: 0 }} 
              transition={{ delay: 0.3 }}
              className="inline-flex items-center gap-3 px-4 py-2 rounded-full border border-white/10 bg-white/5 backdrop-blur-md shadow-[0_0_15px_rgba(0,242,254,0.1)]"
            >
              <span className="flex h-2 w-2 rounded-full bg-primary shadow-[0_0_8px_rgba(0,242,254,0.8)] animate-pulse"></span>
              <span className="text-sm font-semibold text-white tracking-wide uppercase">Elite Fitness Experience</span>
            </motion.div>

            {/* Premium Typography Headline */}
            <div className="relative">
              <motion.h1 
                initial={{ opacity: 0, y: 20 }} 
                animate={{ opacity: 1, y: 0 }} 
                transition={{ delay: 0.4 }}
                className="text-6xl md:text-7xl lg:text-[5.5rem] font-heading text-white leading-[1.1] tracking-tight"
              >
                Sculpt Your <br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-white to-secondary drop-shadow-lg">
                  Ultimate Physique
                </span>
              </motion.h1>
              {/* Decorative Accent under Title */}
              <motion.div 
                initial={{ width: 0 }} 
                animate={{ width: "100px" }} 
                transition={{ delay: 0.8, duration: 0.8 }}
                className="mt-6 h-1 bg-gradient-to-r from-primary to-transparent rounded-full"
              />
            </div>

            <motion.p 
              initial={{ opacity: 0 }} 
              animate={{ opacity: 1 }} 
              transition={{ delay: 0.5 }}
              className="text-gray-400 text-xl font-light max-w-2xl leading-relaxed"
            >
              Step into the future of fitness. Unleash your potential with our cutting-edge AI blueprint, world-class coaching, and a community built for greatness.
            </motion.p>

            {/* Modern Action Buttons */}
            <motion.div 
              initial={{ opacity: 0, y: 15 }} 
              animate={{ opacity: 1, y: 0 }} 
              transition={{ delay: 0.6 }}
              className="flex flex-wrap items-center gap-6"
            >
              {user ? (
                <Link to={dashboardPath} className="group relative">
                  <div className="absolute -inset-1 bg-gradient-to-r from-primary to-secondary rounded-xl blur opacity-25 group-hover:opacity-60 transition duration-500"></div>
                  <button className="relative flex items-center gap-3 bg-white text-background font-bold px-8 py-4 rounded-xl hover:scale-[1.02] transition-transform shadow-xl">
                    Access Dashboard <ArrowRight className="w-5 h-5 transition-transform group-hover:translate-x-1" />
                  </button>
                </Link>
              ) : (
                <Link to="/register" className="group relative">
                  <div className="absolute -inset-1 bg-gradient-to-r from-primary to-secondary rounded-xl blur opacity-30 group-hover:opacity-75 transition duration-500"></div>
                  <button className="relative flex items-center gap-3 bg-primary text-background font-bold px-8 py-4 rounded-xl hover:scale-[1.02] transition-transform shadow-xl hover:shadow-[0_0_20px_rgba(0,242,254,0.4)] text-lg tracking-wide">
                    Start Your Journey <ArrowRight className="w-5 h-5 transition-transform group-hover:translate-x-1" />
                  </button>
                </Link>
              )}
              
              <button className="group flex items-center gap-4 text-white font-medium px-4 py-4 hover:text-primary transition-colors">
                <span className="relative flex items-center justify-center w-14 h-14 rounded-full border border-white/20 bg-white/5 backdrop-blur-sm group-hover:border-primary/50 group-hover:bg-primary/10 transition-all duration-300">
                  <Play className="w-5 h-5 ml-1 fill-current group-hover:scale-110 transition-transform" />
                  {/* Subtle Radar Ring Ping */}
                  <span className="absolute inset-0 rounded-full border border-white/30 animate-ping opacity-20"></span>
                </span>
                <span className="text-lg tracking-wide">Watch Demo</span>
              </button>
            </motion.div>

            {/* Social Proof & Trust Metrics */}
            <motion.div 
              initial={{ opacity: 0 }} 
              animate={{ opacity: 1 }} 
              transition={{ delay: 0.8 }}
              className="pt-10 flex flex-col sm:flex-row gap-8 sm:gap-12 items-start sm:items-center border-t border-white/10"
            >
              <div className="flex items-center gap-4">
                <div className="flex -space-x-3">
                  {avatars.map((src, i) => (
                    <img key={i} src={src} alt="Member" className="w-12 h-12 rounded-full border-2 border-[#0a0a0a] object-cover shadow-lg" />
                  ))}
                  <div className="w-12 h-12 rounded-full border-2 border-[#0a0a0a] bg-surface flex items-center justify-center shadow-lg relative overflow-hidden">
                    <div className="absolute inset-0 bg-primary/20 backdrop-blur-sm"></div>
                    <span className="text-primary text-xs font-bold relative z-10">10K+</span>
                  </div>
                </div>
                <div className="flex flex-col">
                  <div className="flex gap-1">
                    {[...Array(5)].map((_, i) => <Star key={i} className="w-4 h-4 fill-yellow-400 text-yellow-400 drop-shadow-[0_0_5px_rgba(250,204,21,0.5)]" />)}
                  </div>
                  <span className="text-sm text-gray-400 mt-1 font-medium">Trusted worldwide</span>
                </div>
              </div>

              {/* Minimal Divider for Desktop */}
              <div className="hidden sm:block w-px h-12 bg-white/10" />

              <div className="flex items-center gap-6">
                <div>
                  <div className="flex items-baseline gap-1">
                    <p className="text-3xl font-heading font-bold text-white">98</p>
                    <span className="text-primary font-bold">%</span>
                  </div>
                  <p className="text-xs text-gray-500 uppercase tracking-widest mt-1">Success</p>
                </div>
                <div>
                  <div className="flex items-baseline gap-1">
                    <p className="text-3xl font-heading font-bold text-white">50</p>
                    <span className="text-secondary font-bold">+</span>
                  </div>
                  <p className="text-xs text-gray-500 uppercase tracking-widest mt-1">Coaches</p>
                </div>
              </div>
            </motion.div>
          </motion.div>

          {/* Right Content - Hero Visual (Spans 5 columns on LG) */}
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }} 
            animate={{ opacity: 1, scale: 1 }} 
            transition={{ duration: 1, delay: 0.2, type: "spring", stiffness: 50 }}
            className="lg:col-span-5 relative mt-16 lg:mt-0 flex justify-center lg:justify-end"
          >
            {/* Monumental Watermark */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 pointer-events-none select-none overflow-hidden mix-blend-overlay w-full">
              <span className="text-[180px] md:text-[220px] font-heading font-black text-white/5 tracking-tighter leading-none block text-center">GYM<br/>NEXT</span>
            </div>

            <div className="relative group">
              {/* Decorative Circle Behind Image */}
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[90%] aspect-square rounded-full border border-white/5 bg-gradient-to-tr from-surface/50 to-transparent shadow-2xl transition-transform duration-700 group-hover:scale-105" />
              
              <img 
                src="/hero_trainers.png" 
                alt="Fitness Trainers"
                className="relative z-10 w-full max-w-md lg:max-w-none max-h-[650px] object-contain drop-shadow-[0_20px_50px_rgba(0,0,0,0.5)] transition-transform duration-700 group-hover:scale-[1.02]" 
              />
              
              {/* Dynamic Bottom Glow */}
              <div className="absolute -bottom-6 left-1/2 -translate-x-1/2 w-3/4 h-12 bg-primary/30 rounded-full blur-2xl transition-opacity duration-500 group-hover:opacity-70" />

              {/* Floating Glass UI Card - AI Blueprint */}
              <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.8, delay: 1 }}
                className="absolute -left-4 md:-left-16 lg:-left-20 bottom-16 lg:bottom-24 z-20 glass-card p-4 rounded-2xl border border-white/10 shadow-2xl backdrop-blur-xl bg-background/40 max-w-[200px] animate-float"
              >
                <div className="flex items-center gap-3 mb-2">
                  <div className="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center border border-primary/30">
                    <Brain className="w-5 h-5 text-primary" />
                  </div>
                  <div>
                    <h4 className="text-white text-sm font-bold leading-tight">AI Blueprint</h4>
                    <p className="text-xs text-primary font-medium mt-0.5">Ready</p>
                  </div>
                </div>
                <div className="space-y-1.5 mt-3">
                  <div className="h-1.5 w-full bg-surface rounded-full overflow-hidden">
                    <div className="h-full bg-gradient-to-r from-primary to-secondary w-[85%] rounded-full" />
                  </div>
                  <p className="text-[10px] text-gray-400 text-right">Optimization 85%</p>
                </div>
              </motion.div>

              {/* Floating Glass UI Card - Calories Burned */}
              <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.8, delay: 1.2 }}
                className="absolute -right-2 top-20 z-20 glass-card p-4 rounded-xl border border-white/10 shadow-2xl backdrop-blur-xl bg-background/40 animate-float-delayed"
              >
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 rounded-xl bg-secondary/20 flex items-center justify-center border border-secondary/30">
                    <Flame className="w-6 h-6 text-secondary" />
                  </div>
                  <div>
                    <p className="text-[11px] text-gray-400 uppercase tracking-widest font-semibold">Calories</p>
                    <div className="flex items-baseline gap-1">
                      <h4 className="text-white text-xl font-heading font-bold">1,240</h4>
                      <span className="text-xs text-secondary font-medium">kcal</span>
                    </div>
                  </div>
                </div>
              </motion.div>

            </div>
          </motion.div>
        </div>
      </section>

      {/* ─── Stats Bar ─────────────────────────────────────────────── */}
      <section className="border-y border-white/5 bg-surface/30 py-8">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            {stats.map((s, i) => (
              <motion.div key={i} initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }} viewport={{ once: true }}>
                <p className="text-3xl font-bold text-primary">{s.value}</p>
                <p className="text-sm text-gray-400 mt-1">{s.label}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Programs Section ─────────────────────────────────────── */}
      <section className="py-24 relative">
        <div className="container mx-auto px-4">
          <div className="flex items-end justify-between mb-12">
            <div>
              <p className="text-primary text-sm font-medium tracking-widest uppercase mb-2">What We Offer</p>
              <h2 className="text-4xl md:text-5xl font-heading text-white">Explore Our <br />Programs</h2>
            </div>
            <div className="flex gap-3">
              <button onClick={() => scrollCards(-1)} disabled={scrollIdx === 0}
                className="w-11 h-11 rounded-full border border-white/20 flex items-center justify-center text-white hover:bg-white/10 disabled:opacity-30 disabled:cursor-not-allowed transition-colors">
                <ArrowLeft className="w-5 h-5" />
              </button>
              <button onClick={() => scrollCards(1)} disabled={scrollIdx >= programs.length - 3}
                className="w-11 h-11 rounded-full bg-primary text-background flex items-center justify-center hover:bg-primary/90 disabled:opacity-30 disabled:cursor-not-allowed transition-colors">
                <ArrowRight className="w-5 h-5" />
              </button>
            </div>
          </div>

          {/* Cards */}
          <div className="overflow-hidden" ref={cardRef}>
            <motion.div
              animate={{ x: `${-scrollIdx * (100 / 3)}%` }}
              transition={{ type: 'spring', stiffness: 300, damping: 30 }}
              className="flex gap-5">
              {programs.map((prog, i) => {
                const Icon = prog.icon;
                const isActive = i === activeCard;
                return (
                  <motion.div key={i} onClick={() => setActiveCard(i)}
                    whileHover={{ y: -4 }}
                    className={`flex-none w-[calc(33.333%-14px)] min-w-[240px] p-7 rounded-2xl border cursor-pointer transition-all duration-300
                      ${isActive ? 'bg-primary border-primary shadow-[0_0_30px_rgba(0,242,254,0.25)]' : 'bg-surface/50 border-white/10 hover:border-white/20'}`}>
                    <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-5 ${isActive ? 'bg-white/20' : 'bg-white/5'}`}>
                      <Icon className={`w-6 h-6 ${isActive ? 'text-background' : 'text-primary'}`} />
                    </div>
                    <h3 className={`text-xl font-heading mb-3 ${isActive ? 'text-background' : 'text-white'}`}>{prog.title}</h3>
                    <p className={`text-sm leading-relaxed ${isActive ? 'text-background/70' : 'text-gray-400'}`}>{prog.desc}</p>
                    <div className={`mt-5 flex items-center gap-1 text-xs font-medium ${isActive ? 'text-background/80' : 'text-primary'}`}>
                      Learn More <ChevronRight className="w-3 h-3" />
                    </div>
                  </motion.div>
                );
              })}
            </motion.div>
          </div>
        </div>
      </section>

      {/* ─── Transformation Section ─────────────────────────────── */}
      <section className="py-24 bg-surface/20">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            {/* Left — Image */}
            <motion.div initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.7 }}
              className="relative">
              <div className="relative rounded-2xl overflow-hidden border border-white/10">
                <img src="/gym_transform.png" alt="Gym Transformation"
                  className="w-full h-[500px] object-cover" />
                <div className="absolute inset-0 bg-gradient-to-t from-background/60 to-transparent" />
              </div>
              {/* Badge */}
              <div className="absolute bottom-6 left-6 glass-card px-5 py-3 border-primary/30 flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-primary/20 border border-primary/40 flex items-center justify-center">
                  <Zap className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <p className="text-white font-bold text-sm">AI-Powered</p>
                  <p className="text-primary text-xs">Personalized Plans</p>
                </div>
              </div>
            </motion.div>

            {/* Right — Content */}
            <motion.div initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.7, delay: 0.2 }}
              className="space-y-7">
              <p className="text-primary text-sm font-medium tracking-widest uppercase">Why Choose Us</p>
              <h2 className="text-4xl md:text-5xl lg:text-6xl font-heading text-white leading-tight">
                Transform your physique with our fitness plan.
              </h2>
              <p className="text-gray-400 text-lg leading-relaxed">
                Our platform combines the power of AI-driven recommendations, expert coaches, and a supportive community to help you achieve and exceed your fitness goals — faster than ever.
              </p>

              <div className="space-y-4">
                {[
                  { icon: Brain, title: 'AI Oracle', desc: 'Get a personalized workout and meal plan based on your body metrics' },
                  { icon: Users, title: 'Expert Coaches', desc: 'Book sessions with certified professionals who specialize in your goal' },
                  { icon: Trophy, title: 'Track Progress', desc: 'Monitor your sessions, confirm bookings and stay on track effortlessly' },
                ].map((item, i) => (
                  <div key={i} className="flex items-start gap-4">
                    <div className="w-11 h-11 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center flex-shrink-0">
                      <item.icon className="w-5 h-5 text-primary" />
                    </div>
                    <div>
                      <h4 className="font-semibold text-white">{item.title}</h4>
                      <p className="text-sm text-gray-400 mt-0.5">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>

              <div className="flex gap-4 pt-2">
                {user ? (
                   <Link to={dashboardPath}
                     className="flex items-center gap-2 bg-primary text-background font-bold px-7 py-3.5 rounded-xl hover:bg-primary/90 transition-all hover:shadow-[0_0_20px_rgba(0,242,254,0.3)]">
                     Go to Dashboard <ArrowRight className="w-4 h-4" />
                   </Link>
                ) : (
                   <>
                     <Link to="/register"
                       className="flex items-center gap-2 bg-primary text-background font-bold px-7 py-3.5 rounded-xl hover:bg-primary/90 transition-all hover:shadow-[0_0_20px_rgba(0,242,254,0.3)]">
                       Get Started <ArrowRight className="w-4 h-4" />
                     </Link>
                     <Link to="/login"
                       className="flex items-center gap-2 border border-white/20 text-white font-medium px-7 py-3.5 rounded-xl hover:bg-white/5 transition-all">
                       Sign In
                     </Link>
                   </>
                )}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ─── CTA Banner ─────────────────────────────────────────────── */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
            className="glass-card p-14 text-center border-primary/20 bg-gradient-to-br from-primary/5 via-transparent to-secondary/5 relative overflow-hidden">
            <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-primary/50 to-transparent" />
            <div className="absolute inset-x-0 bottom-0 h-px bg-gradient-to-r from-transparent via-secondary/30 to-transparent" />
            <Zap className="w-14 h-14 text-primary mx-auto mb-5" />
            <h2 className="text-4xl md:text-5xl font-heading text-white mb-4">Ready to Transform?</h2>
            <p className="text-gray-400 text-lg max-w-xl mx-auto mb-8">
              Join thousands of members already crushing their fitness goals with Gym Next Gen.
            </p>
            {user ? (
              <Link to={dashboardPath}
                className="inline-flex items-center gap-2 bg-primary text-background font-bold px-10 py-4 rounded-xl text-base hover:bg-primary/90 hover:shadow-[0_0_30px_rgba(0,242,254,0.4)] transition-all">
                Go to Dashboard <ArrowRight className="w-5 h-5" />
              </Link>
            ) : (
              <Link to="/register"
                className="inline-flex items-center gap-2 bg-primary text-background font-bold px-10 py-4 rounded-xl text-base hover:bg-primary/90 hover:shadow-[0_0_30px_rgba(0,242,254,0.4)] transition-all">
                Start for Free <ArrowRight className="w-5 h-5" />
              </Link>
            )}
          </motion.div>
        </div>
      </section>

    </div>
  );
};

export default HomePage;
