import { useState, useRef } from 'react';
import { Link, useNavigate, Navigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { motion } from 'framer-motion';
import {
  Play, ArrowRight, ArrowLeft, Dumbbell, Flame,
  Apple, Brain, ChevronRight, Star, Users, Trophy, Zap
} from 'lucide-react';

const programs = [
  {
    icon: Flame,
    title: 'Cardio Strength',
    desc: 'High-intensity cardio workouts designed to build your cardiovascular endurance and burn maximum calories.',
    color: 'bg-primary text-background',
    accent: 'border-primary',
  },
  {
    icon: Dumbbell,
    title: 'Fat Loss',
    desc: 'Targeted protocols combining resistance training and strategic cardio to accelerate fat burning.',
    color: 'bg-surface text-white',
    accent: 'border-white/10',
  },
  {
    icon: Trophy,
    title: 'Muscle Gain',
    desc: 'Progressive overload programs engineered to maximize hypertrophy and build raw strength.',
    color: 'bg-surface text-white',
    accent: 'border-white/10',
  },
  {
    icon: Apple,
    title: 'Nutrition',
    desc: 'Science-backed meal planning and macro tracking for optimal body composition and performance.',
    color: 'bg-surface text-white',
    accent: 'border-white/10',
  },
  {
    icon: Brain,
    title: 'AI Blueprint',
    desc: 'Personalized plans generated by our ML model based on your biological metrics and goals.',
    color: 'bg-surface text-white',
    accent: 'border-white/10',
  },
];

const stats = [
  { value: '10K+', label: 'Satisfied Members', icon: Users },
  { value: '50+', label: 'Expert Coaches', icon: Trophy },
  { value: '200+', label: 'Workout Programs', icon: Dumbbell },
  { value: '98%', label: 'Success Rate', icon: Star },
];

const avatars = [
  'https://randomuser.me/api/portraits/men/32.jpg',
  'https://randomuser.me/api/portraits/women/44.jpg',
  'https://randomuser.me/api/portraits/men/56.jpg',
];

const HomePage = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [activeCard, setActiveCard] = useState(0);
  const [scrollIdx, setScrollIdx] = useState(0);
  const cardRef = useRef(null);

  // Determine dashboard route for logged-in users
  const dashboardPath = user ? (user.role === 'Admin' ? '/admin' : user.role === 'Coach' ? '/coach' : '/customer') : '';

  const scrollCards = (dir) => {
    const next = scrollIdx + dir;
    if (next >= 0 && next <= programs.length - 3) {
      setScrollIdx(next);
      setActiveCard(next);
    }
  };

  return (
    <div className="overflow-x-hidden">

      {/* ─── Hero Section ─────────────────────────────────────────── */}
      <section className="relative min-h-[90vh] flex items-center">
        {/* Background Glow */}
        <div className="absolute inset-0 pointer-events-none overflow-hidden">
          <div className="absolute -top-1/4 -left-1/4 w-[600px] h-[600px] bg-primary/5 rounded-full blur-3xl" />
          <div className="absolute top-1/4 right-0 w-[400px] h-[600px] bg-secondary/5 rounded-full blur-3xl" />
        </div>

        <div className="container mx-auto px-4 grid grid-cols-1 lg:grid-cols-2 gap-12 items-center relative z-10">
          {/* Left Content */}
          <motion.div initial={{ opacity: 0, x: -40 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.7 }}
            className="space-y-8">

            {/* Social Proof */}
            <div className="flex items-center gap-3">
              <div className="flex -space-x-2">
                {avatars.map((src, i) => (
                  <img key={i} src={src} alt="" className="w-9 h-9 rounded-full border-2 border-background object-cover" />
                ))}
              </div>
              <div>
                <p className="text-white font-semibold text-sm">10K+ Satisfied Members</p>
                <div className="flex gap-0.5 mt-0.5">
                  {[...Array(5)].map((_, i) => <Star key={i} className="w-3 h-3 fill-yellow-400 text-yellow-400" />)}
                </div>
              </div>
            </div>

            {/* Headline */}
            <div>
              <motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}
                className="text-5xl md:text-6xl lg:text-7xl font-heading text-white leading-tight">
                Helps for your<br />
                <span className="text-primary">ideal body</span>{' '}
                fitness
              </motion.h1>
              <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }}
                className="mt-5 text-gray-400 text-lg max-w-md leading-relaxed">
                Motivate yourself with benefits and positive reinforcement. Get personalized plans, coach bookings, and AI-powered progress tracking.
              </motion.p>
            </div>

            {/* CTAs */}
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.6 }}
              className="flex flex-wrap items-center gap-4">
              {user ? (
                <Link to={dashboardPath}
                  className="flex items-center gap-2 bg-primary text-background font-bold px-8 py-4 rounded-xl hover:bg-primary/90 hover:shadow-[0_0_25px_rgba(0,242,254,0.4)] transition-all text-base">
                  Go to Dashboard <ArrowRight className="w-5 h-5" />
                </Link>
              ) : (
                <Link to="/register"
                  className="flex items-center gap-2 bg-primary text-background font-bold px-8 py-4 rounded-xl hover:bg-primary/90 hover:shadow-[0_0_25px_rgba(0,242,254,0.4)] transition-all text-base">
                  Start Training <ArrowRight className="w-5 h-5" />
                </Link>
              )}
              <button
                className="flex items-center gap-3 text-white font-medium px-4 py-4 hover:text-primary transition-colors group">
                <span className="w-12 h-12 rounded-full border-2 border-white/20 flex items-center justify-center group-hover:border-primary/50 transition-colors">
                  <Play className="w-4 h-4 fill-current ml-0.5" />
                </span>
                Watch Demo
              </button>
            </motion.div>

            {/* Quick Stats */}
            <div className="flex gap-8 pt-4 border-t border-white/10">
              <div>
                <p className="text-3xl font-bold text-primary">50+</p>
                <p className="text-xs text-gray-500 mt-1">Expert Coaches</p>
              </div>
              <div>
                <p className="text-3xl font-bold text-secondary">200+</p>
                <p className="text-xs text-gray-500 mt-1">Programs</p>
              </div>
              <div>
                <p className="text-3xl font-bold text-white">98%</p>
                <p className="text-xs text-gray-500 mt-1">Success Rate</p>
              </div>
            </div>
          </motion.div>

          {/* Right — Hero Image */}
          <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.8 }}
            className="relative flex justify-center lg:justify-end">
            {/* Large watermark text */}
            <div className="absolute inset-0 flex items-center justify-center pointer-events-none select-none overflow-hidden">
              <span className="text-[130px] font-heading text-white/3 tracking-widest -rotate-90 translate-x-32">FITNESS</span>
            </div>
            <div className="relative">
              <img src="/hero_trainers.png" alt="Fitness Trainers"
                className="relative z-10 max-h-[520px] object-contain drop-shadow-2xl" />
              {/* Glow under image */}
              <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-48 h-8 bg-primary/20 rounded-full blur-xl" />
            </div>
          </motion.div>
        </div>
      </section>

      {/* ─── Stats Bar ─────────────────────────────────────────────── */}
      <section className="border-y border-white/5 bg-surface/30 py-8">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            {stats.map((s, i) => (
              <motion.div key={i} initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }} viewport={{ once: true }}>
                <p className="text-3xl font-bold text-primary">{s.value}</p>
                <p className="text-sm text-gray-400 mt-1">{s.label}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── Programs Section ─────────────────────────────────────── */}
      <section className="py-24 relative">
        <div className="container mx-auto px-4">
          <div className="flex items-end justify-between mb-12">
            <div>
              <p className="text-primary text-sm font-medium tracking-widest uppercase mb-2">What We Offer</p>
              <h2 className="text-4xl md:text-5xl font-heading text-white">Explore Our <br />Programs</h2>
            </div>
            <div className="flex gap-3">
              <button onClick={() => scrollCards(-1)} disabled={scrollIdx === 0}
                className="w-11 h-11 rounded-full border border-white/20 flex items-center justify-center text-white hover:bg-white/10 disabled:opacity-30 disabled:cursor-not-allowed transition-colors">
                <ArrowLeft className="w-5 h-5" />
              </button>
              <button onClick={() => scrollCards(1)} disabled={scrollIdx >= programs.length - 3}
                className="w-11 h-11 rounded-full bg-primary text-background flex items-center justify-center hover:bg-primary/90 disabled:opacity-30 disabled:cursor-not-allowed transition-colors">
                <ArrowRight className="w-5 h-5" />
              </button>
            </div>
          </div>

          {/* Cards */}
          <div className="overflow-hidden" ref={cardRef}>
            <motion.div
              animate={{ x: `${-scrollIdx * (100 / 3)}%` }}
              transition={{ type: 'spring', stiffness: 300, damping: 30 }}
              className="flex gap-5">
              {programs.map((prog, i) => {
                const Icon = prog.icon;
                const isActive = i === activeCard;
                return (
                  <motion.div key={i} onClick={() => setActiveCard(i)}
                    whileHover={{ y: -4 }}
                    className={`flex-none w-[calc(33.333%-14px)] min-w-[240px] p-7 rounded-2xl border cursor-pointer transition-all duration-300
                      ${isActive ? 'bg-primary border-primary shadow-[0_0_30px_rgba(0,242,254,0.25)]' : 'bg-surface/50 border-white/10 hover:border-white/20'}`}>
                    <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-5 ${isActive ? 'bg-white/20' : 'bg-white/5'}`}>
                      <Icon className={`w-6 h-6 ${isActive ? 'text-background' : 'text-primary'}`} />
                    </div>
                    <h3 className={`text-xl font-heading mb-3 ${isActive ? 'text-background' : 'text-white'}`}>{prog.title}</h3>
                    <p className={`text-sm leading-relaxed ${isActive ? 'text-background/70' : 'text-gray-400'}`}>{prog.desc}</p>
                    <div className={`mt-5 flex items-center gap-1 text-xs font-medium ${isActive ? 'text-background/80' : 'text-primary'}`}>
                      Learn More <ChevronRight className="w-3 h-3" />
                    </div>
                  </motion.div>
                );
              })}
            </motion.div>
          </div>
        </div>
      </section>

      {/* ─── Transformation Section ─────────────────────────────── */}
      <section className="py-24 bg-surface/20">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            {/* Left — Image */}
            <motion.div initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.7 }}
              className="relative">
              <div className="relative rounded-2xl overflow-hidden border border-white/10">
                <img src="/gym_transform.png" alt="Gym Transformation"
                  className="w-full h-[500px] object-cover" />
                <div className="absolute inset-0 bg-gradient-to-t from-background/60 to-transparent" />
              </div>
              {/* Badge */}
              <div className="absolute bottom-6 left-6 glass-card px-5 py-3 border-primary/30 flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-primary/20 border border-primary/40 flex items-center justify-center">
                  <Zap className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <p className="text-white font-bold text-sm">AI-Powered</p>
                  <p className="text-primary text-xs">Personalized Plans</p>
                </div>
              </div>
            </motion.div>

            {/* Right — Content */}
            <motion.div initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.7, delay: 0.2 }}
              className="space-y-7">
              <p className="text-primary text-sm font-medium tracking-widest uppercase">Why Choose Us</p>
              <h2 className="text-4xl md:text-5xl lg:text-6xl font-heading text-white leading-tight">
                Transform your physique with our fitness plan.
              </h2>
              <p className="text-gray-400 text-lg leading-relaxed">
                Our platform combines the power of AI-driven recommendations, expert coaches, and a supportive community to help you achieve and exceed your fitness goals — faster than ever.
              </p>

              <div className="space-y-4">
                {[
                  { icon: Brain, title: 'AI Oracle', desc: 'Get a personalized workout and meal plan based on your body metrics' },
                  { icon: Users, title: 'Expert Coaches', desc: 'Book sessions with certified professionals who specialize in your goal' },
                  { icon: Trophy, title: 'Track Progress', desc: 'Monitor your sessions, confirm bookings and stay on track effortlessly' },
                ].map((item, i) => (
                  <div key={i} className="flex items-start gap-4">
                    <div className="w-11 h-11 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center flex-shrink-0">
                      <item.icon className="w-5 h-5 text-primary" />
                    </div>
                    <div>
                      <h4 className="font-semibold text-white">{item.title}</h4>
                      <p className="text-sm text-gray-400 mt-0.5">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>

              <div className="flex gap-4 pt-2">
                {user ? (
                   <Link to={dashboardPath}
                     className="flex items-center gap-2 bg-primary text-background font-bold px-7 py-3.5 rounded-xl hover:bg-primary/90 transition-all hover:shadow-[0_0_20px_rgba(0,242,254,0.3)]">
                     Go to Dashboard <ArrowRight className="w-4 h-4" />
                   </Link>
                ) : (
                   <>
                     <Link to="/register"
                       className="flex items-center gap-2 bg-primary text-background font-bold px-7 py-3.5 rounded-xl hover:bg-primary/90 transition-all hover:shadow-[0_0_20px_rgba(0,242,254,0.3)]">
                       Get Started <ArrowRight className="w-4 h-4" />
                     </Link>
                     <Link to="/login"
                       className="flex items-center gap-2 border border-white/20 text-white font-medium px-7 py-3.5 rounded-xl hover:bg-white/5 transition-all">
                       Sign In
                     </Link>
                   </>
                )}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ─── CTA Banner ─────────────────────────────────────────────── */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
            className="glass-card p-14 text-center border-primary/20 bg-gradient-to-br from-primary/5 via-transparent to-secondary/5 relative overflow-hidden">
            <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-primary/50 to-transparent" />
            <div className="absolute inset-x-0 bottom-0 h-px bg-gradient-to-r from-transparent via-secondary/30 to-transparent" />
            <Zap className="w-14 h-14 text-primary mx-auto mb-5" />
            <h2 className="text-4xl md:text-5xl font-heading text-white mb-4">Ready to Transform?</h2>
            <p className="text-gray-400 text-lg max-w-xl mx-auto mb-8">
              Join thousands of members already crushing their fitness goals with Gym Next Gen.
            </p>
            {user ? (
              <Link to={dashboardPath}
                className="inline-flex items-center gap-2 bg-primary text-background font-bold px-10 py-4 rounded-xl text-base hover:bg-primary/90 hover:shadow-[0_0_30px_rgba(0,242,254,0.4)] transition-all">
                Go to Dashboard <ArrowRight className="w-5 h-5" />
              </Link>
            ) : (
              <Link to="/register"
                className="inline-flex items-center gap-2 bg-primary text-background font-bold px-10 py-4 rounded-xl text-base hover:bg-primary/90 hover:shadow-[0_0_30px_rgba(0,242,254,0.4)] transition-all">
                Start for Free <ArrowRight className="w-5 h-5" />
              </Link>
            )}
          </motion.div>
        </div>
      </section>

    </div>
  );
};

export default HomePage;
